### ISSUE TITLE
Discord login

### ISSUE THREAD

**Issue by mehrdadmms** [RnDAO/tc-serverComm#1]
# Goal
Users should be able to connect their discord account to the website and authenticate using that.

# How 

- [ ] You can use this [guide](https://discord.com/channels/@me/1039226783150641152/1042190503422197811) 
- [ ] Users information should be stored for later authentication, you should use the predefined interfaces specified [here](https://github.com/RnDAO/dbComm/issues/1#issue-1468063144)

# Extra points
Tests (unit and integration test) will upgrade the task to a higher difficulty score

**Comment by Behzad-rabiei** [comment]
Hi, I m working on this issue.
It will be finished on December 7.
it will take one more day if you want tests(unit, integration).

**Comment by mehrdadmms** [comment]
@Behzad-rabiei 
Please also add the tests.

**Comment by mehrdadmms** [comment]
Resolved #3
