### ISSUE TITLE
Fix: member activity widgets

### ISSUE THREAD

**Issue by cyri113** [RnDAO/tc-serverComm#109]
### Member activities widgets.

- [ ] The value should be for today
- [ ] The % should be compared to week before

@Behzad-rabiei please update the code to reflect these. If this is already what they are doing, you can close the issue.

**Comment by Behzad-rabiei** [comment]
question: Let s say the last member activity document in the database is on June 8th. Should we compare this to June 1st document to calculate the percentage change?
percentage change =  ((newValue - oldValue) / oldValue )) * 100
@cyri113

**Comment by Behzad-rabiei** [comment]
for the percentage change, based on the formula we may have different scenarios:

- **Positive Change (Increase):** If the new value is greater than the old value
- **Negative Change (Decrease):** If the new value is less than the old value
- **No Change:**  If the new value is equal to the old value
- Old Value is 0: it creates a division by zero issue. **For this scenario what should I represent for the percentage change!?**

@cyri113

**Comment by Behzad-rabiei** [comment]
> question: Let s say the last member activity document in the database is on June 8th. Should we compare this to June 1st document to calculate the percentage change? percentage change = ((newValue - oldValue) / oldValue )) * 100
> 
> @cyri113 @daniel-ospina

is this correct?
@cyri113

**Comment by Behzad-rabiei** [comment]
> Options:
> 
> 1. Display "N/A" or "Not Available".
> 2. Display "Infinity" or "∞"
> 3. Hide the percentage.
> 
> I suggest we go with option 1: "N/A"

I m fine with all options but what about UI/UX? 
for example how does user know what is N/A meanings?

**Comment by daniel-ospina** [comment]
> > Options:
> > 
> > 1. Display "N/A" or "Not Available".
> > 2. Display "Infinity" or "∞"
> > 3. Hide the percentage.
> > 
> > I suggest we go with option 1: "N/A"
> 
> I m fine with all options but what about UI/UX? for example how does user know what is N/A meanings?

I would simply output a -
