### ISSUE TITLE
New Choreography: DISCORD_FETCH_MEMBERS

### ISSUE THREAD

**Issue by cyri113** [RnDAO/tc-serverComm#114]
# Context

Today, we create a single choreography, `DISCORD_UPDATE_CHANNELS`.

This choreography creates transactions for both the discord-bot and the discord-analyzer.

When we connect a guild, we want to fetch the members from the discord-bot, but we don't need to call the discord-analyzer (we don't have any raw data at this point).

# Solution

In order to stop this from happening, we will create a new choreography called `DISCORD_FETCH_MEMBERS `. 

## New

When a guild is created, then:
- [ ] create a saga with the `DISCORD_FETCH_MEMBERS` choreography

## Refactor
When a guild is updated (period, selectedChannels), then:
- [ ] create a saga with the `DISCORD_UPDATE_CHANNELS` choreography

## Documentation
- https://github.com/RnDAO/tc-messageBroker/issues/35
- https://github.com/RnDAO/tc-discordBot/issues/67

**Comment by scientiststwin** [comment]
This task was completed and merged 29th June
