### ISSUE TITLE
Decentralisation score API endpoint

### ISSUE THREAD

**Issue by cyri113** [RnDAO/tc-serverComm#115]
# Context

See notion link.

# Solution

- [ ] Create a route
- [ ] Create a controller
- [ ] Create the query

# Documentation
- https://www.notion.so/Product-Roadmap-531f72f0dc6e43f697ba60e02fbf3fd3?p=5c73b3b428c74929bd6f9d097b727e4b&pm=s
- https://github.com/RnDAO/tc-uiComm/issues/99

**Comment by scientiststwin** [comment]
[CLOSED] PR was merged and issue should be closed
