### ISSUE TITLE
Send message to discord user

### ISSUE THREAD

**Issue by cyri113** [RnDAO/tc-serverComm#130]
# Context

We should like to send the discord user a message notifying them once the analysis on their guild has been completed.

# Solution

- [ ] Define the message: `Your data import into TogetherCrew is complete! See your insights on your dashboard https://app.togethercrew.com/`
- [ ] Add the following data to the saga: `{ guildId: Snowflake, discordId: Snowflake, message: string, useFallback: bool }`.
- [ ] The message should be published automatically after the analysis is completed.

## Documentation
- https://www.notion.so/Product-Roadmap-531f72f0dc6e43f697ba60e02fbf3fd3?p=c5045e8f31404e7b8d8eb75a6ca94dc6&pm=s
- https://github.com/RnDAO/tc-messageBroker/issues/36
- https://github.com/RnDAO/tc-discordBot/issues/68

**Comment by scientiststwin** [comment]
@cyri113 @amindadgar 
We already have a `created` property next to the guild id. 
So, the data should be something like this: 
```
{ guildId: Snowflake, created: boolean, discordId: Snowflake, message: string, useFallback: bool }
```

**Comment by scientiststwin** [comment]
Should the message field in our data be changed based on the created flag?

**Comment by amindadgar** [comment]
Can't remember properly, Could you clarify what the `created` flag was? @scientiststwin

**Comment by scientiststwin** [comment]
@amindadgar check here please 

https://discord.com/channels/915914985140531240/1121466334564339723

**Comment by scientiststwin** [comment]
[https://github.com/RnDAO/tc-serverComm/pull/139]
PR was merged
