### ISSUE TITLE
Modify Joined Field Logic for Active Members Onboarding Members Breakdown Table

### ISSUE THREAD

**Issue by Behzad-rabiei** [RnDAO/tc-serverComm#161]
### Description:
The aim of this issue is to modify the logic for retrieving the **joined** field in the Active Members Onboarding Members Breakdown Table. Instead of deriving this information based on the latest member activity document, the system should now determine this value based on the **last seven documents** of member activity.

**Comment by Behzad-rabiei** [comment]
@amindadgar Should I aggregate the Ids within the joined field for the last seven documents?

**Comment by amindadgar** [comment]
By aggregate if you mean having all the last 7 documents joined members
together, then yes.
