### ISSUE TITLE
Settings configuration

### ISSUE THREAD

**Issue by mehrdadmms** [RnDAO/tc-serverComm#2]
# Goal
- User is going to determine which server we're going to fetch the information from as well as the specific channels we need to extract the information from.
- User will also specify the period of data we're going to extract.
- User's email will be captured 

# How
- [ ] API for showing all server's user is an admin in 
- [ ] API for showing  all channels of the the selected server
- [ ] API for storing the selected server, specified channels, and the selected period
- [ ] API for updating user profile (for capturing email)

# More information 
To store this information you can use the schema and the infrastructure from this [issue](https://github.com/RnDAO/dbComm/issues/1#issue-1468063144)  

# Extra points
By adding unit and integration test, you'll receive more points (the task will be upgraded to 1000 points)

**Comment by Behzad-rabiei** [comment]
Hi, I m working on this issue.
It will be finished on December 23(including tests and docs)

**Comment by mehrdadmms** [comment]
Resolved by #6
