### ISSUE TITLE
Bot status API

### ISSUE THREAD

**Issue by mehrdadmms** [RnDAO/tc-serverComm#27]
# Goal
- Show bot connection status
- Show bot analysis progress status 

# How
- [Update database schema](https://github.com/RnDAO/tc-dbComm/issues/15)
- Create the necessary APIs
- Tests
- Swagger

**Comment by Behzad-rabiei** [comment]
need the following API:
Get the list of guilds with pagintation (limit, currentpage, filter, sort, ....)

**Comment by mehrdadmms** [comment]
Closed by #26
