### ISSUE TITLE
Dockerfile & Docker Compose

### ISSUE THREAD

**Issue by mehrdadmms** [RnDAO/tc-serverComm#4]
# Goal
- Create dockerfile for tc-serverComm repo
- Create docker-compose to run tc-serverComm environment

# How
- Dockerfile should inherit node 16 as the project is currently running on node 16
- You understand the rest of the requirements by reading the package.json file  
- To run the service we need a docker of mongoDB to store 

# Appendix 
Here's an example of .env file 
`
NODE_ENV=development
PORT=3000
MONGODB_URL=mongodb://127.0.0.1:27017/RnDAO
DISCROD_CLIENT_ID=xxx
DISCORD_CLIENT_SECRET=xxx-
Discord_Callback_URI=http://localhost:3000/api/v1/auth/callback
DISCORD_BOT_TOKEN=xxx
JWT_SECRET=xxx
JWT_ACCESS_EXPIRATION_MINUTES=30
JWT_REFRESH_EXPIRATION_DAYS=30
JWT_DISCORD_REFRESH_EXPIRATION_DAYS=30
`

**Comment by Ankurobelisk** [comment]
started working on this task.
